name: graphql_types_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  build: ^2.2.1
  collection: ^1.16.0
  path: ^1.8.0

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.1.7
  build_test: ^2.1.5
  lints: ^1.0.0
  test: ^1.16.0
