name: graphql_types_builder
description: Generates GraphQL types from a JSON schema.
version: 0.1.0
homepage: https://freewaymx.github.io/graphql_types_builder/
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  build: ^2.2.1
  collection: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.1.7
  build_test: ^2.1.5
  lints: ^1.0.0
  test: ^1.16.0
